name: Driver API_VERSION checks
on:
  pull_request:
    paths:
      - 'driver/ppm_fillers.c'
      - 'driver/bpf/fillers.h'

jobs:
  paths-filter:
    runs-on: ubuntu-latest
    outputs:
      driver_api_changed: ${{ steps.filter.outputs.driver_api }}
    steps:
    - uses: actions/checkout@v2
    - uses: dorny/paths-filter@v2
      id: filter
      with:
        filters: |
          driver_api:
            - 'driver/API_VERSION'

  driver-api:
    runs-on: ubuntu-22.04
    permissions:
      pull-requests: write
    needs: paths-filter
    if: needs.paths-filter.outputs.driver_api_changed == 'false'
    steps:
      - name: Check driver API_VERSION
        uses: mshick/add-pr-comment@v2
        with:
          message: |
            Please double check **driver/API_VERSION** file. See [versioning](https://github.com/falcosecurity/libs/blob/master/driver/README.VERSION.md#api-version-number).
