apiVersion: apps/v1
kind: Deployment
metadata:
  name: disallowed-pod-deployment
  namespace: falco-event-generator
  labels:
    app.kubernetes.io/name: disallowed-pod-deployment
    app.kubernetes.io/part-of: falco-event-generator
    falco.rules: Create-Disallowed-Pod
    message: Creating-pod-with-image-outside-of-allowed-images
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: disallowed-pod-busybox
  template:
    metadata:
      labels:
        app.kubernetes.io/name: disallowed-pod-busybox
        app.kubernetes.io/part-of: falco-event-generator
    spec:
      containers:
        - name: busybox
          image: busybox
          command: ["/bin/sh", "-c", "while true; do echo sleeping; sleep 3600; done"]
