apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: write-privileges-role
  namespace: falco-event-generator
  labels:
    app.kubernetes.io/name: write-privileges-role
    app.kubernetes.io/part-of: falco-event-generator
    falco.rules: ClusterRole-With-Write-Privileges-Created
    message: Creating-role-with-write-privileges
rules:
- apiGroups:
    - ""
  resources:
    - "pods"
  verbs:
    - create
