apiVersion: apps/v1
kind: Deployment
metadata:
  name: vanilla-deployment
  namespace: falco-event-generator
  labels:
    app.kubernetes.io/name: vanilla-deployment
    app.kubernetes.io/part-of: falco-event-generator
    falco.rules: K8s-Deployment-Created
    message: Creating-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: vanilla-busybox
  template:
    metadata:
      labels:
        app.kubernetes.io/name: vanilla-busybox
        app.kubernetes.io/part-of: falco-event-generator
    spec:
      containers:
        - name: busybox
          image: busybox
          command: ["/bin/sh", "-c", "while true; do echo sleeping; sleep 3600; done"]
