apiVersion: v1
kind: Service
metadata:
  name: vanilla-service
  namespace: falco-event-generator
  labels:
    app.kubernetes.io/name: vanilla-service
    app.kubernetes.io/part-of: falco-event-generator
    falco.rules: K8s-Service-Created
    message: Creating-service
spec:
  type: ClusterIP
  ports:
    - port: 80
  selector:
    app: busybox